# LLM Model Configuration
model:
  model_name: "claude-3-sonnet-20240229"
  api_key: ""
  max_tokens: 4096
  temperature: 0.7

# Embedding Model Configuration
embedding:
  model_name: "all-mpnet-base-v2"
  dimension: 768
  batch_size: 32

# Database Configuration
database:
  db_url: "postgresql://rag_test:rag_test@localhost:5432/rag_test"
  pool_size: 10
  max_queries: 50000

# Application Settings
app:
  chunk_size: 1000
  chunk_overlap: 200
  vector_store_path: "data/vector_store"
  max_context_length: 4000
  supported_file_types:
    - ".txt"
    - ".md"
    - ".pdf"
    - ".csv"
    - ".json"
    - ".ipynb"

# UI Settings
ui:
  terminal_width: 100
  max_history_display: 5
  syntax_highlighting: true
  show_metadata: true
  date_format: "%Y-%m-%d %H:%M:%S"

# Logging Configuration
logging:
  level: "INFO"
  file: "app.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size: 10485760  # 10MB
  backup_count: 5

# RAG Settings
rag:
  max_chunks_per_query: 5
  similarity_threshold: 0.7
  min_chunk_length: 100
  max_context_chunks: 10